### ISSUE TITLE
Search commands as a motion

### ISSUE THREAD

**Issue by danth** [danth/pathfinder.vim#6]
Implement the use of search commands (`/`) as a motion.

As I suggested [here](https://www.reddit.com/r/vim/comments/gqw3lc/a_plugin_to_calculate_the_most_efficient_movement/frv6hvc?utm_source=share&utm_medium=web2x), a way to get at least *some* functionality could be:
1. Find the [shortest unique substring](https://drops.dagstuhl.de/opus/volltexte/2016/6804/pdf/LIPIcs-ISAAC-2016-34.pdf) of the file which starts from the target position
2. Convert that into a search command
3. Select either the search or the standard movement path depending on the number of keypresses required for each

Using searches in combination with other motions seems like a more difficult problem to tackle.

**Comment by aryabhatta-dey** [comment]
I would approach this issue like how would a human who knows about all the Vim motions, marks and / would do something. 

First I think we should give the special marks, gg, G and other such 1/2 keystroke motions the highest value. 

Then coming to search let's say the one way of getting somewhere is "} 3W". Another way is doing a search entering 3 letters let's say and moving there. I think above a certain line count if the, let say 10, the goal is not to move to the start of a sentence or paragraph we should prioritize search. Why? Well with 3 alphabets nearly everything unique can be identified well. Another thing is I am doing "} 3W" it takes some thinking to do the 3W part. After the initial "}" there is a split delay the user will go through before putting in the 3W. / with 3 alphabets seems to me the less choppy option in this case. What do you think? Fundamentally I believe if two approaches provide the same functionality with nearly the same number of keystrokes I prefer the more smoother option, one that requires less active thinking and is more lazy. It's like how the top Vim golf solution appear impractical to come up with.

We could give the user the choice for the keystrokes in which the system will prioritize search results over motions with a sane default like 2. What do you think? We should go after this after 12, 7. That will save us some code rewrites.

**Comment by AlphaMycelium** [comment]
I think this sounds like a good idea. Some additions to your suggestion:

- Disable searches by putting the setting to a negative value.
- Completing #4 first would make a nice starting point for this code. Feel free to re-assign that if you want to take it on too.

I've started working on 12, once I've made a commit I'll open a draft PR to track progress.

**Comment by aryabhatta-dey** [comment]
That's cool. I will take on #4. You finish #7 #12. Then give me a week. I will come up with a PR draft. Then together we should be able to polish it up
